### ISSUE TITLE
Feature Request: Migrate `AWS::IAM::Policy` to inline policy of the `AWS::IAM::Role`

### ISSUE THREAD

**Issue by r-heimann** [aws-solutions/quota-monitor-for-aws#210]
**Is your feature request related to a problem? Please describe.**

I noticed that quota-monitor-for-aws creates various `AWS::IAM::Policy`, which are then added to 1 `AWS::IAM::Role`. This is considered bad-practice and the policy should be added directly to the `AWS::IAM::Role` as an inline policy.

**Describe the feature you'd like**

No `AWS::IAM::Policy` exists and the policies are added directly to the `AWS::IAM::Role`.
This will also solve issues with untagged `AWS::IAM::Policy`. Right now only `AWS::IAM::Role` tagging through CloudFormation.

**Additional context**

Examples:

<img width="1232" alt="image" src="https://github.com/user-attachments/assets/94afb2ab-2205-40b0-aad2-38f9ae46e59d" />

**Comment by sanjay-reddy-kandi** [comment]
Thank you for raising this, adding this to our backlog.

**Comment by r-heimann** [comment]
Thanks for checking! It seems like i mistook `AWS::IAM::Policy` for `AWS::IAM::ManagedPolicy`.
I would still recommend going away from `AWS::IAM::Policy` because (currently) it does not support drift detection:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html

Putting the IAM Policy directly into the `AWS::IAM::Role` would also increase the deployment speed using CloudFormation, since it doesn't have to manage 2 different resources. Here is a simple example in CloudFormation adding the policy directly in an `AWS::IAM::Role`:

```yaml
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies: # <---
        - PolicyName: "InlinePolicy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: "LogAccess"
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt LogGroup.Arn
```
